# Use the official Node.js image as the base image
FROM node:latest

# Generate a random JWT secret key during the build process
RUN JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n') && \
    echo "JWT_SECRET=$JWT_SECRET" >> /etc/environment

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Adding docker wait tool
ENV WAIT_VERSION 2.12.1
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Command to run the application
CMD ["npm", "start"]
