# Use the official Node.js image as the base image
FROM node:latest as build-stage

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use NGINX as the base image for serving the static files
FROM nginx:latest

# Copy the build output from the build stage to NGINX's default public directory
COPY --from=build-stage /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 443

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
