version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  test:
    build:
      context: ./backend
      dockerfile: DockerFile.test
    depends_on:
      - mongodb
    tty: true  # Enable terminal input
    stdin_open: true  # Keep stdin open even if not attached

volumes:
  mongodata:
