FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=mydatabase
ENV MONGO_USERNAME=user
ENV MONGO_PASSWORD=userpassword
ENV MONGO_DBNAME=userdata

# Copy initialization script
COPY init-mongo.js /docker-entrypoint-initdb.d/
