# Use the official Node.js image as the base image
FROM node:latest as build-stage

# Set the working directory inside the container
WORKDIR /app

# Set backend server address for build to work
ENV REACT_APP_BACKEND_URL="http://backend:5000"

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

RUN chmod +x ./scripts/env-config.sh

# Use NGINX as the base image for serving the static files
FROM nginx:latest

# Copy the build output from the build stage to NGINX's default public directory
COPY --from=build-stage /app/build /usr/share/nginx/html

# RUN echo "location /env-config.js {\\n alias /usr/share/nginx/html/scripts/env-config.js;\\n}" >> /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Adding docker wait tool
ENV WAIT_VERSION 2.12.1
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
