# Use a Node.js base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Generate a random JWT secret key during the build process
RUN JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n') && \
    echo "JWT_SECRET=$JWT_SECRET" >> /etc/environment

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on (if applicable)
# EXPOSE 3000

# Adding docker wait tool
ENV WAIT_VERSION 2.12.1
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Command to run your tests
CMD ["npm", "test"]
